### PR TITLE
Fixes #2 - Fix the HackerEarth API

### LINKED ISSUE #2: Fix the HackerEarth API
**Describe the bug**
Fix the HackerEarth API as it always shows penname is no longer available even if it is available. Update the backend API code accordingly.

**To Reproduce**
Enter any username and hit enter. The HackerEarth API always fails.

**Expected behavior**
All the APIs displayed should be working properly.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by IanFindlay**
## Issue that this pull request solves

Closes: #2 

## Proposed changes

The problem was that even when the username isn't found on the HackerEarth site the status code the website returns is 200. I found a way to identify the 404 page by changing the axios request to a 'get' instead of a 'head' - in order to get the data response - and looking within that data for a '404 error' element. 

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

File: backend/controllers/hackerearth.js [hunk 1]
```diff
@@ -5,12 +5,13 @@ const hackerearth = async username => {
 	let result = {};
 	if (username) {
 		await axios
-			.head(urlList.hackerearth + username)
+			.get(urlList.hackerearth + username)
 			.then(response => {
+				is404PageRegex = /404 error/g
```
Comment (Aman-Codes) [inline backend/controllers/hackerearth.js]:
```suggestion
				const is404PageRegex = /404 error/g;
```

**Review by Aman-Codes — CHANGES_REQUESTED** [review]
